// gen_fixtures regenerates testdata/compact/*.jsonl from a deterministic
// seed. Committed to the repo so the fixtures can be reproduced without
// trusting whatever shell+jq invocations produced them originally.
//
// Run from the repo root:
//
//	go run ./tests/engine/gen_fixtures
//
// The script always writes the same bytes for the same seed. If you
// need to evolve a fixture, change the seed AND the golden files in
// the same commit so the test catches drift.
//
// Size choices (documented here per task requirement):
//   - session-huge-bash.jsonl: ~200 KB — one bash tool result that is
//     large enough to trigger Layer B under a 12 000-token test budget.
//     The full spec calls for 8 MB but that is impractical for git; 200 KB
//     exercises the same Layer A truncation + Layer B fold code paths.
//   - session-many-edits.jsonl: 50 edit_file calls, each with ~10 KB
//     new_string. Layer A strips the args so the session fits under the
//     claude-opus-4-7 full budget without Layer B.
//   - session-mixed-tools.jsonl: 80 turns mixing read_file, bash,
//     edit_file, write_file with small outputs; no Layer B expected.
//   - session-pathological.jsonl: synthesised at TEST TIME by TestMain
//     (~200 MB); it is never committed to git.
package main

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"strings"

	"github.com/snowshine0216/penelope-agent/internal/schema"
)

const fixturesDir = "testdata/compact"

func main() {
	if err := os.MkdirAll(fixturesDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	writeFixture(fixturesDir+"/session-huge-bash.jsonl", genHugeBash())
	writeFixture(fixturesDir+"/session-many-edits.jsonl", genManyEdits())
	writeFixture(fixturesDir+"/session-mixed-tools.jsonl", genMixedTools())
	fmt.Println("regenerated fixtures in", filepath.Clean(fixturesDir))
}

func writeFixture(path string, msgs []schema.Message) {
	f, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	// First line is a comment that loadFixture() skips (prefix "//").
	fmt.Fprintf(f, "// generated by tests/engine/gen_fixtures; do not edit by hand\n")
	for _, m := range msgs {
		b, err := json.Marshal(m)
		if err != nil {
			panic(err)
		}
		f.Write(b)
		f.WriteString("\n")
	}
}

// genHugeBash builds a 30-turn session where turn 15 contains a single
// bash tool result of ~200 KB. This reliably triggers Layer B under the
// 12 000-token tight budget used in compact_realcase_test.go.
func genHugeBash() []schema.Message {
	r := rand.New(rand.NewSource(1))
	msgs := []schema.Message{}
	for i := 1; i <= 30; i++ {
		msgs = append(msgs, schema.Message{Role: schema.RoleUser, Content: fmt.Sprintf("turn %d question", i)})
		if i == 15 {
			// One huge bash result. ~200 KB so the file stays git-friendly
			// but Layer B reliably engages under the 12 000-token test budget.
			args, _ := json.Marshal(map[string]string{"command": "find / -type f 2>/dev/null"})
			msgs = append(msgs, schema.Message{
				Role: schema.RoleAssistant,
				ToolCalls: []schema.ToolCall{{
					ID:        fmt.Sprintf("call_huge_%d", i),
					Name:      "bash",
					Arguments: args,
				}},
			})
			body := strings.Repeat(randLine(r)+"\n", 4000) // ~200 KB
			msgs = append(msgs, schema.Message{
				Role:       schema.RoleTool,
				Content:    body,
				ToolCallID: fmt.Sprintf("call_huge_%d", i),
			})
		} else {
			msgs = append(msgs, schema.Message{Role: schema.RoleAssistant, Content: fmt.Sprintf("turn %d answer", i)})
		}
	}
	return msgs
}

// genManyEdits builds a 50-turn session of edit_file calls each with a
// ~10 KB new_string. Layer A strips the large arguments so the session
// stays under the claude-opus-4-7 full budget without needing Layer B.
func genManyEdits() []schema.Message {
	r := rand.New(rand.NewSource(2))
	msgs := []schema.Message{}
	for i := 1; i <= 50; i++ {
		msgs = append(msgs, schema.Message{Role: schema.RoleUser, Content: fmt.Sprintf("edit %d please", i)})
		args, _ := json.Marshal(map[string]string{
			"path":       fmt.Sprintf("file_%d.go", i),
			"new_string": strings.Repeat(randLine(r)+"\n", 200), // ~10 KB
		})
		msgs = append(msgs, schema.Message{
			Role: schema.RoleAssistant,
			ToolCalls: []schema.ToolCall{{
				ID:        fmt.Sprintf("call_edit_%d", i),
				Name:      "edit_file",
				Arguments: args,
			}},
		})
		msgs = append(msgs, schema.Message{
			Role: schema.RoleTool, Content: "ok",
			ToolCallID: fmt.Sprintf("call_edit_%d", i),
		})
	}
	return msgs
}

// genMixedTools builds an 80-turn session that cycles through
// read_file, bash, edit_file, and write_file with small outputs.
// No Layer B is expected under the full claude-opus-4-7 budget.
func genMixedTools() []schema.Message {
	r := rand.New(rand.NewSource(3))
	msgs := []schema.Message{}
	tools := []string{"read_file", "bash", "edit_file", "write_file"}
	for i := 1; i <= 80; i++ {
		msgs = append(msgs, schema.Message{Role: schema.RoleUser, Content: fmt.Sprintf("turn %d", i)})
		tool := tools[i%len(tools)]
		args, _ := json.Marshal(map[string]string{"path": fmt.Sprintf("f%d.go", i)})
		msgs = append(msgs, schema.Message{
			Role: schema.RoleAssistant,
			ToolCalls: []schema.ToolCall{{
				ID:        fmt.Sprintf("call_%s_%d", tool, i),
				Name:      tool,
				Arguments: args,
			}},
		})
		msgs = append(msgs, schema.Message{
			Role:       schema.RoleTool,
			Content:    randLine(r) + " " + randLine(r),
			ToolCallID: fmt.Sprintf("call_%s_%d", tool, i),
		})
	}
	return msgs
}

func randLine(r *rand.Rand) string {
	const alpha = "abcdefghijklmnopqrstuvwxyz "
	b := make([]byte, 50)
	for i := range b {
		b[i] = alpha[r.Intn(len(alpha))]
	}
	return string(b)
}
